create table mock_products (
	id INT,
	name VARCHAR(50),
	description TEXT,
	price VARCHAR(50),
	wholesale_price VARCHAR(50),
	discount INT,
	art VARCHAR(50)
);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (1, 'Ergotamine Tartrate', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', '$3110.07', '$1293.74', null, null);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (2, 'Hydrocodone Bitartrate and Acetaminophen', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '$4776.22', '$990.76', 75, '420434507-7');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (3, 'TRICLOSAN', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', '$4313.12', '$3627.28', 21, '623001716-4');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (4, 'Ketorolac Tromethamine', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '$3105.56', '$2213.76', null, null);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (5, 'Acetaminophen, Pamabrom and Pyrilamine maleate', 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', '$2654.54', '$2804.74', 46, '571985230-1');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (6, 'ALCOHOL', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.', '$1486.81', '$796.67', 73, '863086528-8');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (7, 'Valsartan and Hydrochlorothiazide', 'Suspendisse potenti.', '$2439.85', '$3881.14', null, null);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (8, 'Geotrichum candidum', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', '$2349.46', '$1316.90', 44, '111426981-6');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (9, 'Gabapentin', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', '$1827.93', '$2229.68', 76, '103617588-X');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (10, 'Risperidone', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', '$4117.69', '$2450.22', null, null);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (11, 'Naproxen', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', '$4708.67', '$1678.85', 45, '679696645-7');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (12, 'Rocuronium Bromide', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', '$2820.74', '$2880.58', 30, '996266003-3');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (13, 'LIOTHYRONINE SODIUM', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', '$1463.30', '$263.05', 31, '485211460-9');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (14, 'metronidazole', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', '$4297.28', '$4615.15', null, null);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (15, 'Ibuprofen', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', '$2822.86', '$1225.13', null, null);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (16, 'phoenix dactylifera pollen', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', '$4270.19', '$4005.35', 66, '053464072-9');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (17, 'Cefepime', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', '$3612.51', '$2282.04', null, null);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (18, 'iloperidone', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.', '$3786.36', '$1569.21', 58, '207624976-1');
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (19, 'hydroxyzine pamoate', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '$1929.72', '$1138.71', null, null);
insert into mock_products (id, name, description, price, wholesale_price, discount, art) values (20, 'Hyoscyamine Sulfate, Methenamine, Phenyl Salicylate, Sodium Phosphate Monobasic, Methylene Blue', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '$3047.49', '$2847.78', 51, '115929898-X');
