create table products (
	id INT,
	name VARCHAR(50),
	description TEXT,
	price VARCHAR(50),
	wholesale_price VARCHAR(50),
	discount INT,
	art VARCHAR(50)
);
insert into products (id, name, description, price, wholesale_price, discount, art) values (4, 'Pantalon Blanco', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 1520.00, 1200.00, 15, 125);
insert into products (id, name, description, price, wholesale_price, discount, art) values (5, 'Pantalon Negro', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 1600.00, 1300.00, 7, 126);
insert into products (id, name, description, price, wholesale_price, discount, art) values (8, 'Buzo Azul', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 5000.00, 4200.00, 6, 127);
insert into products (id, name, description, price, wholesale_price, discount, art) values (6, 'Buzo Azul', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 2900.00, 2500.00, 6, 128);
insert into products (id, name, description, price, wholesale_price, discount, art) values (7, 'Remera Blanca', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 1200.00, 1000.00, 15, 129);
insert into products (id, name, description, price, wholesale_price, discount, art) values (8, 'Camisa Jean', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 3000.00, 2000.00, 15, 130);
insert into products (id, name, description, price, wholesale_price, discount, art) values (9, 'Remera Marron', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 1000.00, 500.00, 10, 131);
insert into products (id, name, description, price, wholesale_price, discount, art) values (10, 'Jean Oscuro', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 1600.00, 1000.00, 10, 132);
insert into products (id, name, description, price, wholesale_price, discount, art) values (11, 'Chaqueta De Cuero', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 5500.00, 5000.00, 10, 133);
insert into products (id, name, description, price, wholesale_price, discount, art) values (12, 'Remera Estampado', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 1200.00, 1000.00, 15, 134);
insert into products (id, name, description, price, wholesale_price, discount, art) values (13, 'Pantalon Negro 2', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 2200.00, 1200.00, 15, 135);
insert into products (id, name, description, price, wholesale_price, discount, art) values (14, 'Campera Negra', 'Lorem ipsum dolor sit amet consectetur adipiscing elit vitae senectus varius phasellus condimentum torquent, eu et laoreet fringilla mi nibh dui est eleifend cras litora. Sollicitudin conubia senectus aliquet penatibus dis torquent non nibh magna ullamcor', 4000.00, 3000.00, 15, 136);

